apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  bank-account-rest-service
  name:  bank-account-rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  bank-account-rest-service
  template:
    metadata:
      labels:
        name:  bank-account-rest-service
    spec:
      containers:
        - env:
          - name: spring.application.name
            value: "bank-account-rest-service"
          - name: spring.data.redis.cluster.nodes
            value: gemfire-server-0:6379
          - name: spring.data.redis.client-type
            value: JEDIS
          - name: spring.profiles.active
            value: redis
#          - name: spring.data.gemfire.pool.locators
#            valueFrom:
#              configMapKeyRef:
#                name: gemfire1-config
#                key: locators
          image: cloudnativedata/bank-account-rest-service:0.0.3-SNAPSHOT
          name: bank-account-rest-service
          imagePullPolicy: Always
#          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: bank-account-rest-service
spec:
  selector:
    name: bank-account-rest-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  type: LoadBalancer