apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  bank-account-rest-service
  name:  bank-account-rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  bank-account-rest-service
  template:
    metadata:
      labels:
        name:  bank-account-rest-service
    spec:
      containers:
        - env:
          - name: spring.data.gemfire.pool.locators
            valueFrom:
              configMapKeyRef:
                name: gemfire1-config
                key: locators
          image: cloudnativedata/bank-account-rest-service:0.0.2-SNAPSHOT
          name: account-rest-service
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: bank-account-rest-service
spec:
  selector:
    name: bank-account-rest-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  type: LoadBalancer