rabbitmq:
  streaming:
    replay: true
server:
  port: 0
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: fraud-ml-pipeline
  cloud:
    function:
      definition: modelSupplier
    stream:
      binder:
        connection-name-prefix: ${spring.application.name}
      bindings:
        modelSupplier-out-0:
          destination: fraud-model
          connection-name-prefix: ${spring.application.name}
          group: ${spring.application.name}
          contentType: application/json
          consumer:
            concurrency: 1
            container-type: stream
            maxAttempts: 2147483647
      rabbit:
        bindings:
          modelSupplier-out-0:
            consumer:
              container-type: stream
  rabbitmq:
    listener:
      type: stream
management:
  endpoints:
    web:
      exposure:
        include: info, health
