apiVersion: gemfire.vmware.com/v1
kind: GemFireCluster
metadata:
  name: gemfire1
spec:
  image: registry.tanzu.vmware.com/pivotal-gemfire/vmware-gemfire:9.15.0
  locators:
    replicas: 1
  servers:
    replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gemfire-locator
spec:
  selector:
    gemfire.vmware.com/app: gemfire1-locator
  ports:
    - name: management
      port: 7070
      targetPort: 7070
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: LoadBalancer