apiVersion: "tanzu.vmware.com/v1"
kind: SpringCloudGatewayRouteConfig
metadata:
  name: obp-account-route-config
spec:
  service:
    name: obp-account-service
    ssoEnabled: true
  routes:
    - predicates:
        - Path=/api/obp/v4.0.0/banks/{bankId}/accounts/{accountId}
        - Method=GET
      tags:
        - account
      title: "Get Account by ID"
      description: "Retrieves information for a specific bank account."
    - predicates:
        - Path=/api/obp/v4.0.0/banks/{bankId}/accounts
        - Method=POST
      tags:
        - account
      title: "Create Bank Account"
      description: "Retrieves information for a specific bank account."