spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: bank-account-sink
#  data:
#    gemfire:
#      pool:
#        locators:
#          cloud: localhost[10334]
  cloud:
    function.definition: bankAccountConsumer
    stream:
      bindings:
        bankAccountConsumer-in-0:
          destination: banking-account
          group: ${spring.application.name}
          consumer:
            concurrency: 1
            container-type: stream
      rabbit:
        bindings:
          bankAccountConsumer-in-0:
            consumer:
              container-type: stream
  rabbitmq:
    listener:
      type: stream
management:
  endpoints:
    web:
      exposure:
        include: info, health
  wavefront:
    application:
      name: ${spring.application.name}
      service-name: ${spring.application.name}
