spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: bank-account-sink
  cloud:
    function:
      definition: bankAccountConsumer
    stream:
      function:
        bindings:
          bankAccountConsumer-in-0: input
          bankAccountConsumer-out-0: output
      binder:
        connection-name-prefix: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: info, health