spring:
  data:
    gemfire:
      locators: localhost[10200]
      cache:
        name: gf2-server1
        server:
         port: 10210
gemfire:
  gemfire-for-redis-port: 6279
  remote-distributed-system-id: 1