spring:
  data:
    gemfire:
      locators: localhost[10100]
      cache:
        name: server1
        server:
         port: 10110
gemfire:
  gemfire-for-redis-port: 6179
  remote-distributed-system-id: 2