apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  bank-rest-service
  name:  bank-rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  bank-rest-service
  template:
    metadata:
      labels:
        name:  bank-rest-service
    spec:
      containers:
        - env:
            - name: spring.data.gemfire.pool.locators
              valueFrom:
                configMapKeyRef:
                  name: gemfire1-config
                  key: locators
          image: cloudnativedata/bank-rest-service:0.0.1-SNAPSHOT
          name: bank-rest-service
          imagePullPolicy: Always
