apiVersion: v1
kind: Service
metadata:
  name: apache-geode-config-server-service
spec:
  selector:
    name: apache-geode-config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888