apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
type: Opaque
stringData:
  rabbitmq-password: "CHANGEME"
data:
  rabbitmq-erlang-cookie: "WXhMZlhqRWtCTTZVb3REbWcyOHJpSHdxUG9qMG1VWnM="
