apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hare
spec:
  replicas: 1
  image: pivotalrabbitmq/rabbitmq-stream
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi
  persistence:
    storage: 3Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_shovel_management
      - rabbitmq_stream
      - rabbitmq_stream_management
      - rabbitmq_stream_prometheus
      - rabbitmq_federation_management
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: hare
spec:
  service:
    type: LoadBalancer