apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  service:
    type: LoadBalancer
  replicas: 3
  image: rabbitmq:3.12.4-management
  resources:
    requests:
      cpu: 900m
      memory: 1Gi
  persistence:
    storage: 3Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      - rabbitmq_stream
      - rabbitmq_stream_management