apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  service:
    type: LoadBalancer
  replicas: 1
  image: rabbitmq:3.12.4-management
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 300m
      memory: 1Gi
  persistence:
    storage: 3Gi
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
      - rabbitmq_shovel
      - rabbitmq_stream
      - rabbitmq_stream_management
      - rabbitmq_stream_prometheus