apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  account-global-service
  name:  account-global-service
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  account-global-service
  template:
    metadata:
      labels:
        name:  account-global-service
    spec:
      containers:
        - env:
          - name: POSTGRES_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-db-app-user-db-secret
                key: username
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-db-app-user-db-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-db-app-user-db-secret
                key: database
          - name: ConnectionString
            value: Host=postgres-db;Database=$(POSTGRES_DB);Username=$(POSTGRES_DB_USERNAME);Password=$(POSTGRES_DB_PASSWORD)
          - name: ASPNETCORE_hostBuilder__reloadConfigOnChange
            value: "false"
          image: cloudnativedata/account.global.service:1.0.0
          name: account-global-service
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always