rabbitmq:
  streaming:
    replay: true
server:
  port: 5080
spring:
  application:
    name: fraud-detection
  cloud:
    function:
      definition: detectFraudFunction;modelConsumer
      http:
        POST: detectFraudFunction
    stream:
      binder:
        connection-name-prefix: ${spring.application.name}
      bindings:
        detectFraudFunction-in-0:
          destination: fraud-model-in
          connection-name-prefix: ${spring.application.name}
          group: ${spring.application.name}
          contentType: application/json
        detectFraudFunction-out-0:
          destination: fraud-model-out
          connection-name-prefix: ${spring.application.name}
          group: ${spring.application.name}
          contentType: application/json
        modelConsumer-in-0:
          destination: fraud-model
          connection-name-prefix: ${spring.application.name}
          group: ${spring.application.name}
          contentType: application/json
          consumer:
            concurrency: 1
            container-type: stream
            maxAttempts: 2147483647
      rabbit:
        bindings:
          modelConsumer-in-0:
            consumer:
              container-type: stream
          detectFraudFunction-in-0:
            consumer:
              container-type: stream
          detectFraudFunction-out-0:
            consumer:
              container-type: stream
  rabbitmq:
    listener:
      type: stream
