CREATE TABLE ACCOUNTS (
    ACCT_ID  VARCHAR2(50)  NOT NULL,
    BANK_ID  VARCHAR2(50)  NOT NULL,
	ACCT_LABEL  VARCHAR2(50) NOT NULL,
	ACCT_NUMBER VARCHAR2(50) NOT NULL,
	ACCT_PRODUCT_CD VARCHAR2(50) NOT NULL,
	ACCT_ROUTINGS VARCHAR2(50) NOT NULL,
	ACCT_VIEWS_BASIC  VARCHAR2(50),
	ACCT_BALANCE NUMBER(10,4) DEFAULT ON NULL 0,
	PRIMARY KEY(ACCT_ID, BANK_ID)
);