server:
  port: 8081
spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name: bank-geode-sink
  data:
    gemfire:
      pool:
        locators:
          cloud: localhost[10334]
  cloud:
    function.definition: bankConsumer
    stream:
      bindings:
        bankConsumer-in-0:
          destination: banking.bank
          group: bankingBankStream
          consumer:
            concurrency: 1
            container-type: stream
      rabbit:
        bindings:
          bankConsumer-in-0:
            consumer:
              container-type: stream
  rabbitmq:
    listener:
      type: stream
    stream:
      host: localhost