server:
  port: 8081
spring:
  application:
    name: bank-geode-sink
  data:
    gemfire:
      pool:
        locators:
          cloud: localhost[10334]
  cloud:
    function.definition: bankConsumer
    stream:
      bindings:
        bankConsumer-in-0:
          destination: banking.bank
          group: bankingBankStream
          consumer:
            concurrency: 1
            container-type: stream
      rabbit:
        bindings:
          bankConsumer-in-0:
            consumer:
              container-type: stream
  rabbitmq:
    listener:
      type: stream
    stream:
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      wavefront:
        api-token: 7fa9942d-a4b7-4cbe-97b0-796d2b2fc074
        uri: https://demo.wavefront.com

wavefront:
  application:
    name: banking
