apiVersion: v1
kind: Service
metadata:
  name: bank-account-rest-service
spec:
  selector:
    name: bank-account-rest-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4001
  type: LoadBalancer