logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
        hibernate: error

server:
  port: 0
spring:
  application:
    name: banking-atm-geode-sink
  data:
    gemfire:
      pool:
        locators:
          cloud: localhost[10334]
  cloud:
    function.definition: atmConsumer
    stream:
      bindings:
        atmConsumer-in-0:
          destination: banking.atm
          group: atmBankStream
          consumer:
            concurrency: 1
            container-type: stream
      rabbit:
        bindings:
          atmConsumer-in-0:
            consumer:
              container-type: stream
  rabbitmq:
    listener:
      type: stream
    stream:
      host: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      wavefront:
        api-token: 7fa9942d-a4b7-4cbe-97b0-796d2b2fc074
        uri: https://demo.wavefront.com

wavefront:
  application:
    name: banking
