apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run:  account-global-consumer
  name:  account-global-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      name:  account-global-consumer
  template:
    metadata:
      labels:
        name:  account-global-consumer
    spec:
      containers:
        - env:
          - name: spring_rabbitmq_host
            value: "rabbitmq"
          - name: spring_rabbitmq_username
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: username
          - name: spring_rabbitmq_password
            valueFrom:
              secretKeyRef:
                name: rabbitmq-default-user
                key: password
          - name: spring_rabbitmq_virtualHost
            value: streaming
          - name: POSTGRES_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-db-app-user-db-secret
                key: username
          - name: POSTGRES_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-db-app-user-db-secret
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-db-app-user-db-secret
                key: database
          - name: ConnectionString
            value: Host=postgres-db;Database=$(POSTGRES_DB);Username=$(POSTGRES_DB_USERNAME);Password=$(POSTGRES_DB_PASSWORD)
          - name: ASPNETCORE_hostBuilder__reloadConfigOnChange
            value: "false"
          image: cloudnativedata/account.global.consumer:1.0.0
          name: account-global-consumer
#          imagePullPolicy: IfNotPresent
          imagePullPolicy: Always